[package]
name = "rustemon"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.203", features = ["derive"]}
reqwest = {version = "0.12.5", features = ["json"]}
tokio = {version = "1.38.0",features = ["full"]}
serde_json = "1.0.118"
